layout_spectrum: 0.342036658199504
typography_spectrum: 0.04996187658980489
color:
  brandStrength: 0.8603386806789786
  lightness: 0.8772901792544872
  saturation: 0.754078141413629
  rhythmicContrast: 0.19732106407172978
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6796e988-c96d-41cd-947e-c24e869fa284.png
name: Tjuvholmen Ventures
navigation:
  - name: Tjuvholmen Ventures Homepage
    url: tjuvholmenventures.no
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6cc5d707-d630-43d1-ad6a-75e87c121034.ico
title: A startup building startups
description: Fueling the Scandinavian startup scene
