layout_spectrum: 0.342036658199504
typography_spectrum: 0.9200018078554422
color:
  brandStrength: 0.6610833110753447
  lightness: 0.3772440163884312
  saturation: 0.8739195859525353
  rhythmicContrast: 0.8205485069192946
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6796e988-c96d-41cd-947e-c24e869fa284.png
name: Tjuvholmen Ventures
navigation:
  - name: Tjuvholmen Ventures Homepage
    url: tjuvholmenventures.no
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6cc5d707-d630-43d1-ad6a-75e87c121034.ico
title: A startup building startups
description: Fueling the Scandinavian startup scene
